// oxlint-disable one-var, no-magic-numbers, capitalized-comments
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const root = process.cwd(),
  pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8")),
  version = pkg.version as string,
  banner = `/* ai-skill-html-planner v${version} */`,
  distDir = join(root, "dist"),
  outputFiles = ["planner.css", "planner.min.css", "planner.js", "planner.min.js"],
  EXIT_FAILURE = 1,
  LEADING_DOT = 1,
  SUCCESS_STATUS = 0;

const runBuild = (env: Record<string, string>, config: string): void => {
  const result = spawnSync("bunx", ["vite", "build", "-c", config], {
    cwd: root,
    env: { ...process.env, ...env },
    stdio: "inherit",
  });
  if (result.status !== SUCCESS_STATUS) {
    process.stderr.write(`Build failed for ${config}\n`);
    process.exit(result.status ?? EXIT_FAILURE);
  }
};

const prependBanner = (fileName: string): void => {
  const filePath = join(distDir, fileName);
  if (!existsSync(filePath)) {
    process.stderr.write(`Missing expected dist file: ${fileName}\n`);
    process.exit(EXIT_FAILURE);
  }
  const text = readFileSync(filePath, "utf8"),
    hasBanner = text.startsWith(banner);
  if (hasBanner) {
    return; // Idempotent — banner already present.
  }
  writeFileSync(filePath, `${banner}\n${text}`);
};

const extractAllowlist = (cssText: string): string[] => {
  // Drop comment blocks so URLs inside them (e.g. tailwindcss.com in the
  // license banner) do not leak bogus entries into the allowlist.
  const noComments = cssText.replace(/\/\*[\s\S]*?\*\//g, ""),
    classes = new Set<string>(),
    classPattern = /\.-?[_a-zA-Z][_a-zA-Z0-9-]*/g;
  let match: RegExpExecArray | null = classPattern.exec(noComments);
  while (match !== null) {
    const charBefore = noComments[match.index - LEADING_DOT];
    if (charBefore !== ":") {
      classes.add(match[0].slice(LEADING_DOT)); // Strip leading dot.
    }
    match = classPattern.exec(noComments);
  }
  return [...classes].sort();
};

runBuild({ PLANNER_MIN: "1" }, "vite.config.ts");
runBuild({}, "vite.config.ts");

const minCss = readFileSync(join(distDir, "planner.min.css"), "utf8"),
  allowlist = extractAllowlist(minCss),
  allowlistPath = join(root, "src", "runtime", "allowlist.generated.ts");
writeFileSync(
  allowlistPath,
  `// Generated by scripts/build.ts — do not edit.\nexport const ALLOWLIST: string[] = [${allowlist.map((entry) => `"${entry}"`).join(", ")}];\n`,
);

runBuild({ PLANNER_MIN: "1" }, "vite.runtime.config.ts");
runBuild({}, "vite.runtime.config.ts");

for (const fileName of outputFiles) {
  prependBanner(fileName);
}

console.log("\nBuild summary:");
for (const fileName of outputFiles) {
  const size = readFileSync(join(distDir, fileName)).length;
  console.log(`  dist/${fileName}: ${size} bytes`);
}
console.log(`  allowlist entries: ${allowlist.length}`);
